### PR TITLE
Version 3

### PR DESCRIPTION
**Pull request by c-vetter**
Based on  #296

I'd like to trim the code and enable use-cases that do not support pre-IE9 browsers, alongside the current IE6+ support. To that end, I created a new build script that splits a modern and a legacy version from each source script.

This also includes a first stab at having proper build targets for CJS, ESM, and global namespace. The difference from the previous strategy being that the decision for a specific export happens *before* the file is delivered to the end user.

I consider this an alpha version and would like your feedback on whether you think this is worthwhile and will be welcome. I'd like to PR this into a v3 branch, if you were to create one.

### CODE REVIEW

**Comment by Necroskillz** [comment]
Can `onloadCSS` also be exported as cjs/esm etc. Unless I'm missing something it's currently not possible to use it (require/import) as a module.

**Comment by rasenplanscher** [comment]
> @Necroskillz 
> 
> Can `onloadCSS` also be exported as cjs/esm etc. Unless I'm missing something it's currently not possible to use it (require/import) as a module.

You are correct, there is actually a ticket on this issue: #171 

I commented there about this issue a moment ago.

**Comment by rasenplanscher** [comment]
@scottjehl @zachleat Would you kindly take a look? I think this is almost release-worthy. I'd appreciate your input 🙂

**Comment by rasenplanscher** [comment]
It's still lacking documentation, which I will add soon.

**Comment by scottjehl** [comment]
Wow, @rasenplanscher this is some extensive work. We really appreciate all the help you're bringing here. We're pretty slammed with project work at FG at the moment so it's going to take us a bit to get a look through this one - particularly given that there's a fair amount of changes in here. Thankfully you've split it out nicely so reviewing by commits should be reasonable.

We hope to be in touch on it soon thanks again

**Comment by rasenplanscher** [comment]
@scottjehl 
Thank you for the heads-up 🙂 I know those phases, all good.
Looking forward to your feedback.

**Comment by lidqqq** [comment]
I think it's a great change!

Do you have a plan to proceed this PR ?

**Comment by rasenplanscher** [comment]
@lidqqq 
Thanks for the revival! 🙂
I'll update the PR to make it mergeable 👍

**Pull request closed without merging**
