### PR TITLE
Smaller footprint and it should fix #29

### LINKED ISSUE #29: Relative paths do not work
```
loadCSS("../dist/css/style.css");
```

If I'm calling loadCSS this way, it does not work. The problem is IMHO on [line 29](https://github.com/filamentgroup/loadCSS/blob/master/loadCSS.js#L29). 

loadCSS does not found relatively called stylesheet and `media` attribute is remaining on `only x` value.

On my project I can fix it easily, but maybe someone will experience the same problem.

### PR DESCRIPTION
**Pull request by zachleat**

### CODE REVIEW

**Comment by scottjehl** [comment]
oh! yeah I like that.

**Comment by scottjehl** [comment]
Good coverage on `ownerNode`? Looks good. Opposite of `sheet` I guess? :) https://github.com/filamentgroup/grunticon/blob/master/tasks/grunticon/static/grunticon.embed.js#L36

**Comment by matijs** [comment]
What is the rationale for polling using setTimeout in toggleMedia like this?

**Comment by zachleat** [comment]
Of note, `ownerNode` does not work in IE8. So maybe hold off on merging this until the other stuff surrounding onload settles.

**Comment by zachleat** [comment]
@matijs The `media` attribute toggle has to take place after the request has been initiated and is in flight. WebKit adds the stylesheet to document.styleSheets when it’s finished loading. We could use `onload` for this but browser support on Android WebKit (anything less than 4.4) is not there.

**Comment by zachleat** [comment]
Due to IE8 incompat and #29 fixed elegantly by another PR, we can close this.

**Pull request closed without merging**
