### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Marabyte**
Addresses #177 #172 
- Added information about loading the polyfill before the link tag.
- Added example how to load the scripts

### CODE REVIEW

**Comment by scottjehl** [comment]
Thanks - I like the caniuse link.

The second condition doesn't match the expected behavior of the preload script. Source order shouldn't matter, and if it does it's a bug we should address in the js.

The way the script is written currently, it starts running immediately and continues to look for preload links until the onload event fires. Are you finding that that isn't working in certain places?

**Comment by Marabyte** [comment]
I stand corrected. The issue I was having was not because the order I load the scripts and the link but the scripts it self.

I was loading the polyfill first and then the loadCSS function. In the polyfill code is explicit that it requires the loadCSS function but not on the documentation.

I'll update my request.

**Comment by scottjehl** [comment]
great, thank you!

**Comment by scottjehl** [comment]
Thanks again for this. With the landing of the `fall2017` branch, we've cleaned up the Readme a bit and some of these changes won't line up now. I'm thinking that the caniuse support link is still a great thing to add in there, but otherwise I'm pretty sure the instructions are good now. I'm going to close this out but add the link over in the readme before we package up 2.0. Thank you for that idea.

**Pull request closed without merging**
