### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by inoas**
> (note: the newest `rel=preload` pattern is not yet in that readme, but the concepts are the same).
... reading the readme... it is actually there, isn't it?

### CODE REVIEW

**Comment by scottjehl** [comment]
hmm. I don't think it's in the enhancejs readme still. TODO! Would love the help though

**Comment by inoas** [comment]
So you expose cssrelpreload / preloadCSS? and onloadCSS.
At least for me the docs where not lacking so I was wondering why the note was there?!

**Comment by scottjehl** [comment]
It's referencing a different project's readme, which doesn't cover this update yet. I've been behind but it's on my list to update the Enhance repo with our latest workflow.

**Comment by scottjehl** [comment]
We rewrote the readme and I think this is better now. I hope! Thanks.

**Pull request closed without merging**
