### PR TITLE
Do not load a CSS file if a style sheet with the same URL already exists on the webpage

### LINKED ISSUE #236: Possible memory leak when used with the same URL multiple times
At Airbnb, we are using this package to async load some stylesheets. We are also doing some single-page app stuff. When these two things cross paths, and you end up visiting the same page that calls loadCSS with the same URL multiple times via client-side routing, we believe we end up with a memory leak.

Would you be open to changing this package to avoid adding any given stylesheet to the page more than once? One possible solution would be to use a helper function such as:

```js
function hasStyleSheet(url) {
  var ss = document.styleSheets;
  for (var i = 0; i < ss.length; i++) {
    if (ss[i].href === url) { return true; }
  }
  return false;
}
```

cc @jvilk @adamrneary @thaingnguyen

### PR DESCRIPTION
**Pull request by jvilk**
Fixes #236.

### CODE REVIEW

**Comment by jvilk** [comment]
The CI failure seems independent of this change. This is ready for review, as far as I can tell.

**Comment by odahcam** [comment]
Much needed functionality! Awesome!

**Comment by odahcam** [comment]
Much needed functionality! Awesome!

**Comment by jvilk** [comment]
I have added a test, and modified the tests to clean up the DOM to prevent spurious test failures.

**Comment by scottjehl** [comment]
Thanks for the work on this PR, folks. 

I'm unsure that this would be desirable to include as a default. For example, a developer might intentionally re-request a stylesheet of the same URL several times in the course of a session knowing that its caching headers are such that a subsequent request will bring updated rules.

**Comment by jvilk** [comment]
Fair enough. I'll leave this here for you and the community to decide.

**Comment by odahcam** [comment]
Why reload a stylesheet to update CSS rules when you can update all the DOM with JavaScript, that is such a bad practice, right?

Also, you can always put a query string with a version at the end of the url: `<url>/styleshee.css?v=1.0.0`.

**Comment by scottjehl** [comment]
The related issue is closed for now, with a recommendation to somehow avoid making duplicate calls to loadCSS in that particular codebase, but I left an open question to see further discussion is warranted. Thanks everyone.

**Comment by eloyesp** [comment]
In some limited environments (read Shopify for example), adding duplicate calls and a single request makes **a lot** of sense. For example, it would make it possible to have spreadsheets for some components and having a single request when there are multiple instances of each component and having no request for that when there is none...

Also, may be, that is simply another functionality that can be implemented on a different way and chained with this one. (That would make a Unix approach to the issue).

**Pull request closed without merging**
