### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @scottjehl: check the diff with https://github.com/filamentgroup/loadCSS/pull/210/files?w=1

### CODE REVIEW

**Comment by XhmikosR** [comment]
@scottjehl: updated. Keep in mind this PR fixes testing on Windows. Is there something you'd want different?

You can also close #211.

**Comment by XhmikosR** [comment]
@scottjehl: updated to the latest versions.

**Comment by scottjehl** [comment]
Thanks for this, but the changes are too varied in scope for us to review as a whole. We'd love if you would like to re-submit some of the more important changes individually. Thanks so much.

**Comment by XhmikosR** [comment]
@scottjehl: just check each individual patach with `?w=1`. They are pretty straightforward to me.

**Pull request closed without merging**
