### PR TITLE
Fixed incorrect “as” attribute usage

### PR DESCRIPTION
**Pull request by HugoGiraudel**

### CODE REVIEW

**Comment by scottjehl** [comment]
hmm. okay I'm confused. This change reflects what the spec says, which is good. But it also seems to work fine in Canary with `as="style". Any ideas why that'd be?

**Comment by HugoGiraudel** [comment]
I’d say this is an implementation mistake in Canary, because in Chrome Version 48.0.2564.116 (64-bit), using `rel="style"` reports the following in the console:

> <link rel=preload> must have a valid `as` value

**Comment by scottjehl** [comment]
okay. I updated the polyfill too. Does that cover everything? If so we can bump the version...

**Comment by HugoGiraudel** [comment]
I don’t have the project locally, I’m just browsing the files on GitHub, so I hope I did not miss one.

**Comment by HugoGiraudel** [comment]
Missing this one: https://github.com/filamentgroup/loadCSS/blob/ae14a8bb2b2ed86bf547515a800e049029c82498/test/qunit/index.html.

**Comment by HugoGiraudel** [comment]
Done in https://github.com/filamentgroup/loadCSS/pull/147.

**Comment by HugoGiraudel** [comment]
Missing this condition in the script: https://github.com/filamentgroup/loadCSS/blob/2f778f07dd490467d7735fe21593b0aea043c471/test/preload.html#L112.

**Comment by scottjehl** [comment]
I don't think so, no. Since this is a spec polyfill, it's a bug. Make sense?

**Comment by HugoGiraudel** [comment]
If you only intend to polyfill the spec, then `stylesheet` should be enough. However, you started with `style` in the first place and apparently it used to work somewhere (at least for a time), so I don’t know. Your call here.

**Comment by scottjehl** [comment]
Thanks. I think since the bug is in the polyfill, and it's only been out for a couple hours at this point, it's probably the right call to fix the bug to match the spec and tag as 1.1.

Hope that works for folks.

**Comment by HugoGiraudel** [comment]
Should be good. Are you taking over on this or shall I do anything else?

**Comment by scottjehl** [comment]
I think we're all good. Thanks so much for catching the bug!

**Comment by HugoGiraudel** [comment]
No worries. I’ll probably ping you in a GitHub issue over the week-end or next week though because I cannot seem to make v1.0.0 work properly on Sass Guidelines. For some reason, the stylesheet is never being applied. I must be doing something wrong, but can’t put my finger on what. :(

**Pull request merged**
