### PR TITLE
Small rewrite to help Javascript minification tools.

### PR DESCRIPTION
**Pull request by dlemstra**
This is a small rewrite to help Javascript minification tools. The comparison has been done with: https://marijnhaverbeke.nl/uglifyjs.

Current version (https://raw.githubusercontent.com/filamentgroup/loadCSS/master/loadCSS.js)
Ugly version:
Old version: 2357 characters
New version: **616** characters
Saved: 1741 (result is 26.1% of original)

Rewritten version (https://raw.githubusercontent.com/dlemstra/loadCSS/minify-optimization/loadCSS.js)
Ugly version:
Old version: 2435 characters
New version: **551** characters
Saved: 1884 (result is 22.6% of original)

### CODE REVIEW

**Comment by dlemstra** [comment]
After the fixes the result is this:
Ugly version:
Old version: 2415 characters
New version: **566** characters
Saved: 1849 (result is 23.4% of original)

**Comment by scottjehl** [comment]
Thanks for this. Good ideas. Let's pull it in!

One question we have is whether the following is split for any particular reason. Otherwise, looks great!

image

**Comment by dlemstra** [comment]
You need this split because the method calls itself recursively. Without this (https://github.com/dlemstra/loadCSS/commit/88c133c543332b23881117941dabdc66050dbbff) it failed to pass the unit tests.

**Comment by scottjehl** [comment]
weird, I’m seeing tests pass just fine with this combined. I tried it minified too, to be sure. I’m not sure I understand why it’d be any different one way or the other?

**Comment by dlemstra** [comment]
I updated my comment. I thought that piece of code was causing the tests to fail but it passes them perfectly now. Sorry for the confusion.

**Comment by scottjehl** [comment]
thanks again!

**Pull request merged**
